import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';
import worker from '../server/index.mjs';import {hash,now} from '../server/util.mjs';import {cookie} from '../server/auth.mjs';import {snapshot} from '../server/sheets.mjs';
class D1 {
 constructor(){this.db=new DatabaseSync(':memory:');this.db.exec(fs.readFileSync('drizzle/0000_rich_redwing.sql','utf8'));}
 prepare(sql){const db=this.db;return {bind(...args){return {
  async first(){return db.prepare(sql).get(...args)||null;},
  async all(){return {results:db.prepare(sql).all(...args)};},
  async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};}
 };}};}
 async batch(items){this.db.exec('BEGIN');try{const r=[];for(const item of items)r.push(await item.run());this.db.exec('COMMIT');return r;}catch(e){this.db.exec('ROLLBACK');throw e;}}
}
function fixture(){const players=Array.from({length:8},(_,i)=>'P'+i);const grid=[['Spiel-ID','Datum','Spieltag','Handicap-Modus',...players,'Grundsumme','Prüfung'],...Array.from({length:35},(_,i)=>[i+1,46000+Math.floor(i/3),9+Math.floor(i/3),'Pro Spiel',...Array(8).fill(''),'',''])];const rules=[7,3,6,1,1.5,2,6,1e-9,3,2,1].map(x=>[x]);let writes=0;const env={DB:new D1(),APP_ORIGIN:'https://league.test',OWNER_EMAIL:'owner@example.test',SHEETS_TEST:{read:async()=>structuredClone({grid,rules}),write:async(row,values)=>{writes++;grid[row-1].splice(4,8,...values);}}};return{env,grid,get writes(){return writes}};}
async function session(f,role='member',address=role+'@example.test'){const token=crypto.randomUUID().replaceAll('-','').repeat(2);f.env.DB.db.prepare('INSERT OR REPLACE INTO members VALUES(?,?,?,?)').run(address,role,'active',now());f.env.DB.db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await hash(token),address,now()+3600);return cookie(token).split(';')[0];}
const req=(f,path,token,data,origin='https://league.test')=>worker.fetch(new Request('https://league.test/api/'+path,{method:data===undefined?'GET':'POST',headers:{...(token?{Cookie:token}:{}),...(data===undefined?{}:{Origin:origin,'Content-Type':'application/json'})},body:data===undefined?undefined:JSON.stringify(data)}),f.env);
const entries=[{player:0,rank:1},{player:1,rank:2},{player:2,rank:2},{player:3,rank:4}];
test('anonymous cannot read league; members cannot write; managers cannot grant roles',async()=>{const f=fixture();assert.equal((await req(f,'league')).status,401);const m=await session(f);assert.equal((await req(f,'results',m,{})).status,403);const manager=await session(f,'manager');assert.equal((await req(f,'members',manager,{email:'new@example.test',role:'manager'})).status,403);assert.equal(f.writes,0);});
test('owner grants, demotes and revokes managers; stale sessions immediately denied',async()=>{const f=fixture(),owner=await session(f,'owner');let r=await req(f,'members',owner,{email:'new@example.test',role:'manager'});assert.equal(r.status,200);const manager=await session(f,'manager','new@example.test');r=await req(f,'member',owner,{email:'new@example.test',role:'member',status:'active'});assert.equal(r.status,200);assert.equal((await req(f,'league',manager)).status,401);assert.equal((await req(f,'member',owner,{email:'owner@example.test',role:'member',status:'revoked'})).status,400);});
test('cross-origin write rejected before mutation',async()=>{const f=fixture(),owner=await session(f,'owner');assert.equal((await req(f,'members',owner,{email:'other@example.test',role:'member'},'https://evil.test')).status,403);});
test('single-use expiring email token creates a secure cookie',async()=>{const f=fixture();const token='a'.repeat(64);f.env.DB.db.prepare('INSERT INTO members VALUES(?,?,?,?)').run('p@example.test','member','invited',now());f.env.DB.db.prepare('INSERT INTO tokens VALUES(?,?,?)').run(await hash(token),'p@example.test',now()+30);const r=await req(f,'verify',null,{token});assert.equal(r.status,200);assert.match(r.headers.get('Set-Cookie'),/HttpOnly; Secure; SameSite=Lax/);assert.equal((await req(f,'verify',null,{token})).status,401);const expired='b'.repeat(64);f.env.DB.db.prepare('INSERT INTO tokens VALUES(?,?,?)').run(await hash(expired),'p@example.test',now()-1);assert.equal((await req(f,'verify',null,{token:expired})).status,401);});
test('revoked membership cannot redeem an unused email token',async()=>{const f=fixture(),token='c'.repeat(64);f.env.DB.db.prepare('INSERT INTO members VALUES(?,?,?,?)').run('p@example.test','member','revoked',now());f.env.DB.db.prepare('INSERT INTO tokens VALUES(?,?,?)').run(await hash(token),'p@example.test',now()+30);assert.equal((await req(f,'verify',null,{token})).status,403);});
test('manager save preserves fractions, blank absences and retry idempotency',async()=>{const f=fixture(),manager=await session(f,'manager');const s=await snapshot(await f.env.SHEETS_TEST.read());const p={operationId:crypto.randomUUID(),gameId:1,revision:s.revision,entries};let r=await req(f,'results',manager,p);assert.equal(r.status,200,await r.clone().text());assert.deepEqual(f.grid[1].slice(4,12),[3,1.5,1.5,0,'','','','']);r=await req(f,'results',manager,p);assert.equal(r.status,200);assert.equal(f.writes,1);});
test('concurrent manager submissions result in only one write',async()=>{const f=fixture(),manager=await session(f,'manager');const s=await snapshot(await f.env.SHEETS_TEST.read());const p={gameId:1,revision:s.revision,entries};const responses=await Promise.all([req(f,'results',manager,{...p,operationId:crypto.randomUUID()}),req(f,'results',manager,{...p,operationId:crypto.randomUUID()})]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);assert.equal(f.writes,1);});
test('stale previews and corrections without a reason are rejected',async()=>{const f=fixture(),manager=await session(f,'manager');let s=await snapshot(await f.env.SHEETS_TEST.read());await req(f,'results',manager,{operationId:crypto.randomUUID(),gameId:1,revision:s.revision,entries});assert.equal((await req(f,'results',manager,{operationId:crypto.randomUUID(),gameId:2,revision:s.revision,entries})).status,409);s=await snapshot(await f.env.SHEETS_TEST.read());assert.equal((await req(f,'results',manager,{operationId:crypto.randomUUID(),gameId:1,revision:s.revision,entries})).status,400);const r=await req(f,'results',manager,{operationId:crypto.randomUUID(),gameId:1,revision:s.revision,entries,reason:'Falschen Spieler ausgewählt'});assert.equal(r.status,200);const a=f.env.DB.db.prepare("SELECT * FROM audit WHERE action='correct_result'").get();assert.match(a.after_json,/Falschen Spieler/);});
test('uncertain remote write stays locked until owner reconciles it',async()=>{const f=fixture(),manager=await session(f,'manager'),owner=await session(f,'owner');const write=f.env.SHEETS_TEST.write;f.env.SHEETS_TEST.write=async(...args)=>{await write(...args);throw Error('network interrupted');};const s=await snapshot(await f.env.SHEETS_TEST.read());const p={operationId:crypto.randomUUID(),gameId:1,revision:s.revision,entries};assert.equal((await req(f,'results',manager,p)).status,503);assert.ok(f.env.DB.db.prepare('SELECT * FROM gate').get());f.env.DB.db.prepare('UPDATE audit SET created=?').run(now()-200);assert.equal((await req(f,'recover',owner,{})).status,200);assert.equal(f.env.DB.db.prepare('SELECT * FROM gate').get(),undefined);assert.equal(f.env.DB.db.prepare('SELECT status FROM audit WHERE id=?').get(p.operationId).status,'applied');});
test('per-day uses day-start standings while per-game uses preceding game',async()=>{const f=fixture();f.grid[1].splice(4,8,3,2,1,0,0,0,0,0);f.grid[2].splice(4,8,3,2,1,0,0,0,0,0);let s=await snapshot(await f.env.SHEETS_TEST.read());assert.equal(s.games[1].baseline[0],3);f.grid[2][3]='Pro Spieltag';s=await snapshot(await f.env.SHEETS_TEST.read());assert.equal(s.games[1].baseline[0],0);});
