import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';
import worker from '../server/index.mjs';import {hash,now} from '../server/util.mjs';import {cookie} from '../server/auth.mjs';import {snapshot} from '../server/sheets.mjs';
class D1 {
 constructor(){this.db=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())this.db.exec(fs.readFileSync('drizzle/'+file,'utf8'));}
 prepare(sql){const db=this.db;return {bind(...args){return {
  async first(){return db.prepare(sql).get(...args)||null;},
  async all(){return {results:db.prepare(sql).all(...args)};},
  async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};}
 };}};}
 async batch(items){this.db.exec('BEGIN');try{const r=[];for(const item of items)r.push(await item.run());this.db.exec('COMMIT');return r;}catch(e){this.db.exec('ROLLBACK');throw e;}}
}
function fixture(){const players=Array.from({length:8},(_,i)=>'P'+i);const grid=[['Spiel-ID','Datum','Spieltag','Handicap-Modus',...players,'Grundsumme','Prüfung'],...Array.from({length:35},(_,i)=>[i+1,46000+Math.floor(i/3),9+Math.floor(i/3),'Pro Spiel',...Array(8).fill(''),'',''])];const rules=[7,3,6,1,1.5,2,6,1e-9,3,2,1].map(x=>[x]);let writes=0;const mails=[];const env={DB:new D1(),APP_ORIGIN:'https://league.test',OWNER_EMAIL:'owner@example.test',MAIL_TEST:{send:async mail=>{mails.push(mail);return Response.json({id:'sent'});}},SHEETS_TEST:{read:async()=>structuredClone({grid,rules}),write:async(row,values)=>{writes++;grid[row-1].splice(4,8,...values);}}};return{env,grid,mails,get writes(){return writes}};}
async function session(f,role='member',address=role+'@example.test'){const token=crypto.randomUUID().replaceAll('-','').repeat(2);f.env.DB.db.prepare('INSERT OR REPLACE INTO members VALUES(?,?,?,?)').run(address,role,'active',now());f.env.DB.db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await hash(token),address,now()+3600);return cookie(token).split(';')[0];}
const req=(f,path,token,data,origin='https://league.test')=>worker.fetch(new Request('https://league.test/api/'+path,{method:data===undefined?'GET':'POST',headers:{...(token?{Cookie:token}:{}),...(data===undefined?{}:{Origin:origin,'Content-Type':'application/json'})},body:data===undefined?undefined:JSON.stringify(data)}),f.env);
const entries=[{player:0,rank:1},{player:1,rank:2},{player:2,rank:2},{player:3,rank:4}];
test('anonymous cannot read league; members cannot write; managers cannot grant roles',async()=>{const f=fixture();assert.equal((await req(f,'league')).status,401);const m=await session(f);assert.equal((await req(f,'results',m,{})).status,403);const manager=await session(f,'manager');assert.equal((await req(f,'members',manager,{email:'new@example.test',role:'manager'})).status,403);assert.equal(f.writes,0);});
test('login does not reveal whether an address is registered',async()=>{const f=fixture();let r=await req(f,'login',null,{email:'unknown@example.test'});assert.equal(r.status,200);const unknown=await r.json();assert.match(unknown.message,/Wenn diese Adresse freigegeben/);assert.equal(f.mails.length,0);await session(f,'member','known@example.test');r=await req(f,'login',null,{email:'known@example.test'});assert.equal(r.status,200);const known=await r.json();assert.deepEqual(known,unknown);assert.equal(known.registered,undefined);assert.equal(f.mails.length,1);});
test('six-digit code signs in the original browser and remembers it for six months',async()=>{const f=fixture();await session(f,'manager','known@example.test');let r=await req(f,'login',null,{email:'known@example.test'});assert.equal(r.status,200);const code=f.mails[0].text.match(/\n(\d{6})\n/)[1];assert.equal((await req(f,'verify-code',null,{email:'known@example.test',code:'999999'})).status,401);r=await req(f,'verify-code',null,{email:'known@example.test',code});assert.equal(r.status,200);assert.match(r.headers.get('Set-Cookie'),/Max-Age=15552000/);const remembered=r.headers.get('Set-Cookie').split(';')[0];assert.equal((await req(f,'league',remembered)).status,200);assert.equal((await req(f,'verify-code',null,{email:'known@example.test',code})).status,401);});
test('registered login sends a link while revoked access remains blocked',async()=>{const f=fixture();await session(f,'member','known@example.test');let r=await req(f,'login',null,{email:'known@example.test'});assert.equal(r.status,200);assert.equal(f.mails.length,1);f.env.DB.db.prepare("UPDATE members SET status='revoked' WHERE email=?").run('known@example.test');r=await req(f,'login',null,{email:'known@example.test'});assert.equal(r.status,200);assert.equal(f.mails.length,1);});
test('shared join page needs one approval email and activates the verified member',async()=>{const f=fixture(),manager=await session(f,'manager'),member=await session(f,'member','viewer@example.test');let r=await req(f,'join-admin',manager,{status:'open',expiresDays:30,maxUses:2});assert.equal(r.status,200);r=await req(f,'join-status');assert.equal(r.status,200);let data=await r.json();assert.equal(data.open,true);assert.equal(data.maxUses,2);assert.equal(data.uses,0);assert.ok(data.expires>now());r=await req(f,'join-start',null,{name:'Neue Person',email:'new@example.test'});assert.equal(r.status,200,await r.clone().text());assert.equal(f.mails.length,0);assert.equal((await req(f,'join-admin',member)).status,403);data=await (await req(f,'join-admin',manager)).json();assert.equal(data.requests.length,1);assert.equal(data.requests[0].name,'Neue Person');assert.equal(data.requests[0].verified,0);r=await req(f,'join-decision',manager,{email:'new@example.test',action:'approve'});assert.equal(r.status,200,await r.clone().text());assert.equal(f.mails.length,1);assert.equal(f.mails[0].to,'new@example.test');assert.equal(f.env.DB.db.prepare('SELECT role,status FROM members WHERE email=?').get('new@example.test').role,'member');assert.equal(f.env.DB.db.prepare('SELECT status FROM join_requests WHERE email=?').get('new@example.test').status,'approved');const code=f.mails[0].text.match(/\n(\d{6})\n/)[1];r=await req(f,'verify-code',null,{email:'new@example.test',code});assert.equal(r.status,200);assert.equal(f.env.DB.db.prepare('SELECT status FROM members WHERE email=?').get('new@example.test').status,'active');assert.equal(f.env.DB.db.prepare('SELECT status FROM join_requests WHERE email=?').get('new@example.test').status,'activated');});
test('commissioners can close joining and reject requests without sending email or creating access',async()=>{const f=fixture(),manager=await session(f,'manager');assert.equal((await req(f,'join-admin',manager,{status:'open',expiresDays:7,maxUses:''})).status,200);assert.equal((await req(f,'join-start',null,{name:'Rejected Player',email:'reject@example.test'})).status,200);assert.equal(f.mails.length,0);assert.equal((await req(f,'join-decision',manager,{email:'reject@example.test',action:'reject'})).status,200);assert.equal(f.env.DB.db.prepare('SELECT * FROM members WHERE email=?').get('reject@example.test'),undefined);assert.equal((await req(f,'join-admin',manager,{status:'closed'})).status,200);assert.equal((await req(f,'join-start',null,{name:'Late Player',email:'late@example.test'})).status,403);assert.equal((await (await req(f,'join-status')).json()).open,false);});
test('owner grants, demotes and revokes managers; stale sessions immediately denied',async()=>{const f=fixture(),owner=await session(f,'owner');let r=await req(f,'members',owner,{email:'new@example.test',role:'manager'});assert.equal(r.status,200);const manager=await session(f,'manager','new@example.test');r=await req(f,'member',owner,{email:'new@example.test',role:'member',status:'active'});assert.equal(r.status,200);assert.equal((await req(f,'league',manager)).status,401);assert.equal((await req(f,'member',owner,{email:'owner@example.test',role:'member',status:'revoked'})).status,400);});
test('inviting a member sends a direct single-use invitation and supports resend while pending',async()=>{const f=fixture(),owner=await session(f,'owner');let r=await req(f,'members',owner,{email:'new@example.test',role:'member'});assert.equal(r.status,200);assert.equal(f.mails.length,1);assert.equal(f.mails[0].to,'new@example.test');assert.match(f.mails[0].subject,/Einladung/);assert.match(f.mails[0].text,/https:\/\/league\.test\/#token=[a-f0-9]{64}/);r=await req(f,'members',owner,{email:'new@example.test',role:'member'});assert.equal(r.status,200);assert.equal(f.mails.length,2);assert.equal(f.env.DB.db.prepare("SELECT count(*) count FROM audit WHERE action='invite_email'").get().count,1);});
test('owner can resend to an active member and remove the membership',async()=>{const f=fixture(),owner=await session(f,'owner');await session(f,'member','new@example.test');let r=await req(f,'resend-invite',owner,{email:'new@example.test'});assert.equal(r.status,200);assert.equal(f.mails.length,1);assert.equal(f.mails[0].to,'new@example.test');assert.equal(f.env.DB.db.prepare("SELECT count(*) count FROM audit WHERE action='invite_email'").get().count,1);r=await req(f,'remove-member',owner,{email:'new@example.test'});assert.equal(r.status,200);assert.equal(f.env.DB.db.prepare('SELECT * FROM members WHERE email=?').get('new@example.test'),undefined);assert.equal(f.env.DB.db.prepare('SELECT * FROM sessions WHERE email=?').get('new@example.test'),undefined);assert.equal(f.env.DB.db.prepare("SELECT count(*) count FROM audit WHERE action='membership_remove'").get().count,1);});
test('owner cannot be removed and revoked members cannot receive invitations',async()=>{const f=fixture(),owner=await session(f,'owner');assert.equal((await req(f,'remove-member',owner,{email:'owner@example.test'})).status,400);f.env.DB.db.prepare('INSERT INTO members VALUES(?,?,?,?)').run('revoked@example.test','member','revoked',now());assert.equal((await req(f,'resend-invite',owner,{email:'revoked@example.test'})).status,409);assert.equal(f.mails.length,0);});
test('cross-origin write rejected before mutation',async()=>{const f=fixture(),owner=await session(f,'owner');assert.equal((await req(f,'members',owner,{email:'other@example.test',role:'member'},'https://evil.test')).status,403);});
test('single-use expiring email token creates a secure six-month cookie',async()=>{const f=fixture();const token='a'.repeat(64);f.env.DB.db.prepare('INSERT INTO members VALUES(?,?,?,?)').run('p@example.test','member','invited',now());f.env.DB.db.prepare('INSERT INTO tokens VALUES(?,?,?)').run(await hash(token),'p@example.test',now()+30);const r=await req(f,'verify',null,{token});assert.equal(r.status,200);assert.match(r.headers.get('Set-Cookie'),/HttpOnly; Secure; SameSite=Lax; Max-Age=15552000/);assert.equal((await req(f,'verify',null,{token})).status,401);const expired='b'.repeat(64);f.env.DB.db.prepare('INSERT INTO tokens VALUES(?,?,?)').run(await hash(expired),'p@example.test',now()-1);assert.equal((await req(f,'verify',null,{token:expired})).status,401);});
test('revoked membership cannot redeem an unused email token',async()=>{const f=fixture(),token='c'.repeat(64);f.env.DB.db.prepare('INSERT INTO members VALUES(?,?,?,?)').run('p@example.test','member','revoked',now());f.env.DB.db.prepare('INSERT INTO tokens VALUES(?,?,?)').run(await hash(token),'p@example.test',now()+30);assert.equal((await req(f,'verify',null,{token})).status,403);});
test('manager save preserves fractions, blank absences and retry idempotency',async()=>{const f=fixture(),manager=await session(f,'manager');const s=await snapshot(await f.env.SHEETS_TEST.read());const p={operationId:crypto.randomUUID(),gameId:1,revision:s.revision,entries};let r=await req(f,'results',manager,p);assert.equal(r.status,200,await r.clone().text());assert.deepEqual(f.grid[1].slice(4,12),[3,1.5,1.5,0,'','','','']);r=await req(f,'results',manager,p);assert.equal(r.status,200);assert.equal(f.writes,1);});
test('concurrent manager submissions result in only one write',async()=>{const f=fixture(),manager=await session(f,'manager');const s=await snapshot(await f.env.SHEETS_TEST.read());const p={gameId:1,revision:s.revision,entries};const responses=await Promise.all([req(f,'results',manager,{...p,operationId:crypto.randomUUID()}),req(f,'results',manager,{...p,operationId:crypto.randomUUID()})]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);assert.equal(f.writes,1);});
test('stale previews and corrections without a reason are rejected',async()=>{const f=fixture(),manager=await session(f,'manager');let s=await snapshot(await f.env.SHEETS_TEST.read());await req(f,'results',manager,{operationId:crypto.randomUUID(),gameId:1,revision:s.revision,entries});assert.equal((await req(f,'results',manager,{operationId:crypto.randomUUID(),gameId:2,revision:s.revision,entries})).status,409);s=await snapshot(await f.env.SHEETS_TEST.read());assert.equal((await req(f,'results',manager,{operationId:crypto.randomUUID(),gameId:1,revision:s.revision,entries})).status,400);const r=await req(f,'results',manager,{operationId:crypto.randomUUID(),gameId:1,revision:s.revision,entries,reason:'Falschen Spieler ausgewählt'});assert.equal(r.status,200);const a=f.env.DB.db.prepare("SELECT * FROM audit WHERE action='correct_result'").get();assert.match(a.after_json,/Falschen Spieler/);});
test('uncertain remote write stays locked until owner reconciles it',async()=>{const f=fixture(),manager=await session(f,'manager'),owner=await session(f,'owner');const write=f.env.SHEETS_TEST.write;f.env.SHEETS_TEST.write=async(...args)=>{await write(...args);throw Error('network interrupted');};const s=await snapshot(await f.env.SHEETS_TEST.read());const p={operationId:crypto.randomUUID(),gameId:1,revision:s.revision,entries};assert.equal((await req(f,'results',manager,p)).status,503);assert.ok(f.env.DB.db.prepare('SELECT * FROM gate').get());f.env.DB.db.prepare('UPDATE audit SET created=?').run(now()-200);assert.equal((await req(f,'recover',owner,{})).status,200);assert.equal(f.env.DB.db.prepare('SELECT * FROM gate').get(),undefined);assert.equal(f.env.DB.db.prepare('SELECT status FROM audit WHERE id=?').get(p.operationId).status,'applied');});
test('per-day uses day-start standings while per-game uses preceding game',async()=>{const f=fixture();f.grid[1].splice(4,8,3,2,1,0,0,0,0,0);f.grid[2].splice(4,8,3,2,1,0,0,0,0,0);let s=await snapshot(await f.env.SHEETS_TEST.read());assert.equal(s.games[1].baseline[0],3);f.grid[2][3]='Pro Spieltag';s=await snapshot(await f.env.SHEETS_TEST.read());assert.equal(s.games[1].baseline[0],0);});
test('snapshot exposes cumulative points after every game for the standings chart',async()=>{const f=fixture();f.grid[1].splice(4,8,3,2,1,0,0,0,0,0);f.grid[2].splice(4,8,0,3,2,1,0,0,0,0);const s=await snapshot(await f.env.SHEETS_TEST.read());assert.deepEqual(s.games[0].cumulative,[3,2,1,0,0,0,0,0]);assert.deepEqual(s.games[1].cumulative,[3,5,3,1.5,0,0,0,0]);assert.deepEqual(s.games[2].cumulative,s.games[1].cumulative);});
