import {mailConfigured,sendMail} from './mail.mjs';
import {email,random,hash,now,one,all,run,stmt,fail,origin} from './util.mjs';
export const COOKIE='__Host-cl_session';
export const SESSION_AGE=15552000;
export function cookie(token,age=SESSION_AGE){return `${COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`;}
export async function member(request,env,roles){const token=request.headers.get('Cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);if(!token||!/^[a-f0-9]{64}$/.test(token))fail(401,'Bitte anmelden.');const m=await one(env,'SELECT m.email,m.role,m.status FROM sessions s JOIN members m ON s.email=m.email WHERE s.hash=? AND s.expires>?',await hash(token),now());if(!m||m.status!=='active')fail(401,'Bitte erneut anmelden oder Zugang freigeben lassen.');if(roles&&!roles.includes(m.role))fail(403,'Für diese Aktion fehlen die Berechtigungen.');return m;}
async function limit(env,key,max){const t=now(),bucket=Math.floor(t/600);const k=await hash(key)+':'+bucket;const r=await one(env,'INSERT INTO rates(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count',k,t+1200);if(r.count>max)fail(429,'Zu viele Versuche. Bitte in zehn Minuten erneut versuchen.');}
async function sendAccessLink(env,address,invitation=false){
 const token=random(),digest=await hash(token),code=String(crypto.getRandomValues(new Uint32Array(1))[0]%1000000).padStart(6,'0'),codeDigest=await hash(address+':'+code),expiry=now()+900;await env.DB.batch([stmt(env,'DELETE FROM login_codes WHERE email=?',address),stmt(env,'INSERT INTO tokens(hash,email,expires) VALUES(?,?,?)',digest,address,expiry),stmt(env,'INSERT INTO login_codes(hash,email,expires) VALUES(?,?,?)',codeDigest,address,expiry)]);
 const link=origin(env)+'/#token='+token;
 const subject=invitation?'Einladung zur Commander League':'Dein Zugang zur Commander League';
 const intro=invitation?'Du wurdest zur Commander League eingeladen.':'Du möchtest dich bei der Commander League anmelden.';
 const result=await sendMail(env,address,subject,`${intro}\n\nGib diesen Code im bereits geöffneten Browser ein:\n${code}\n\nAlternativ kannst du diesen Link öffnen:\n${link}\n\nCode und Link gelten 15 Minuten und können jeweils nur einmal verwendet werden. Dieses Gerät bleibt danach sechs Monate angemeldet. Falls du diese Nachricht nicht erwartest, kannst du sie ignorieren.`).catch(()=>null);
 if(!result?.ok){await env.DB.batch([stmt(env,'DELETE FROM tokens WHERE hash=?',digest),stmt(env,'DELETE FROM login_codes WHERE hash=?',codeDigest)]);fail(503,'E-Mail konnte gerade nicht versendet werden. Der Zugang bleibt freigegeben und die Einladung kann erneut gesendet werden.');}
}
function displayName(value){if(typeof value!=='string')fail(400,'Bitte gib deinen Namen ein.');const result=value.trim().replace(/\s+/g,' ');if(result.length<2||result.length>80)fail(400,'Der Name muss zwischen 2 und 80 Zeichen lang sein.');return result;}
const joinOpen=s=>s&&s.status==='open'&&(!s.expires||s.expires>now())&&(!s.max_uses||s.uses<s.max_uses);
export async function startLogin(request,env,input){
 const address=email(input.email);if(!mailConfigured(env)||!env.OWNER_EMAIL)fail(503,'E-Mail-Anmeldung ist noch nicht eingerichtet.');
 await limit(env,'ip:'+request.headers.get('CF-Connecting-IP'),12);await limit(env,'email:'+address,3);await limit(env,'global',100);
 await env.DB.batch([stmt(env,'DELETE FROM tokens WHERE expires<?',now()),stmt(env,'DELETE FROM login_codes WHERE expires<?',now()),stmt(env,'DELETE FROM sessions WHERE expires<?',now()),stmt(env,'DELETE FROM rates WHERE expires<?',now())]);
 if(address===email(env.OWNER_EMAIL))await run(env,"INSERT OR IGNORE INTO members(email,role,status,created) VALUES(?,'owner','active',?)",address,now());
 const m=await one(env,'SELECT * FROM members WHERE email=?',address);
 const message='Wenn diese Adresse freigegeben ist, erhältst du gleich einen Anmeldecode. Prüfe bitte auch den Spamordner.';
 if(!m||m.status==='revoked')return {message};
 await sendAccessLink(env,address);
 return {message};
}
export async function joinStatus(env){const s=await one(env,"SELECT status,expires,max_uses,uses,updated FROM join_settings WHERE key='default'");return {open:joinOpen(s),expires:s?.expires||null,maxUses:s?.max_uses||null,uses:s?.uses||0,updated:s?.updated||null};}
export async function startJoin(request,env,input){
 if(!mailConfigured(env)||!env.OWNER_EMAIL)fail(503,'E-Mail-Anmeldung ist noch nicht eingerichtet.');const address=email(input.email),name=displayName(input.name),s=await one(env,"SELECT * FROM join_settings WHERE key='default'");if(!joinOpen(s))fail(403,'Die Liga nimmt über diesen Link derzeit keine Beitrittsanfragen an.');
 const existing=await one(env,'SELECT status FROM members WHERE email=?',address);if(existing)fail(409,existing.status==='revoked'?'Dieser Zugang ist derzeit gesperrt. Bitte wende dich an die Ligaleitung.':'Diese Adresse ist bereits freigegeben. Bitte melde dich an.');
 await limit(env,'join-ip:'+request.headers.get('CF-Connecting-IP'),6);await limit(env,'join-email:'+address,2);await limit(env,'join-global',50);await run(env,'DELETE FROM join_tokens WHERE email=? OR expires<?',address,now());const token=random(),digest=await hash(token);await run(env,'INSERT INTO join_tokens(hash,email,name,expires) VALUES(?,?,?,?)',digest,address,name,now()+1800);const link=origin(env)+'/join#verify='+token;
 const result=await sendMail(env,address,'E-Mail-Adresse für die Commander League bestätigen',`Hallo ${name},\n\nbestätige mit diesem Link deine Beitrittsanfrage zur Commander League:\n${link}\n\nDer Link gilt 30 Minuten und kann einmal verwendet werden. Danach prüft die Ligaleitung deine Anfrage. Falls du diese Nachricht nicht erwartest, kannst du sie ignorieren.`).catch(()=>null);if(!result?.ok){await run(env,'DELETE FROM join_tokens WHERE hash=?',digest);fail(503,'Die Bestätigungs-E-Mail konnte gerade nicht versendet werden. Bitte später erneut versuchen.');}return {message:'Bestätigungs-E-Mail versendet. Öffne den Link darin, um deine Anfrage einzureichen.'};
}
export async function verifyJoin(env,input){
 if(typeof input.token!=='string'||!/^[a-f0-9]{64}$/.test(input.token))fail(400,'Ungültiger Bestätigungslink.');const verified=await one(env,'DELETE FROM join_tokens WHERE hash=? AND expires>? RETURNING email,name',await hash(input.token),now());if(!verified)fail(401,'Der Link ist abgelaufen oder bereits verwendet.');const existing=await one(env,'SELECT status FROM members WHERE email=?',verified.email);if(existing)return {member:true,message:'Diese Adresse ist bereits freigegeben. Du kannst dich jetzt anmelden.'};const pending=await one(env,"SELECT status FROM join_requests WHERE email=? AND status='pending'",verified.email);if(pending)return {message:'Deine bestätigte Anfrage wartet bereits auf die Freigabe durch die Ligaleitung.'};const used=await one(env,"UPDATE join_settings SET uses=uses+1 WHERE key='default' AND status='open' AND (expires IS NULL OR expires>?) AND (max_uses IS NULL OR uses<max_uses) RETURNING uses",now());if(!used)fail(403,'Die Einladung ist inzwischen geschlossen oder ausgeschöpft. Bitte wende dich an die Ligaleitung.');const t=now();await run(env,"INSERT INTO join_requests(email,name,status,created,verified,reviewed,reviewed_by) VALUES(?,?,'pending',?,?,NULL,NULL) ON CONFLICT(email) DO UPDATE SET name=excluded.name,status='pending',created=excluded.created,verified=excluded.verified,reviewed=NULL,reviewed_by=NULL",verified.email,verified.name,t,t);return {message:'E-Mail bestätigt. Deine Anfrage wartet jetzt auf die Freigabe durch die Ligaleitung.'};
}
export async function joinAdmin(env){const status=await joinStatus(env);return {...status,joinUrl:origin(env)+'/join',requests:await all(env,"SELECT email,name,created,verified FROM join_requests WHERE status='pending' ORDER BY created")};}
export async function configureJoin(env,actor,input){
 if(!['open','closed'].includes(input.status))fail(400,'Ungültiger Einladungsstatus.');const before=await one(env,"SELECT * FROM join_settings WHERE key='default'");let expires=null,maxUses=null;if(input.status==='open'){const days=Number(input.expiresDays);if(!Number.isInteger(days)||days<1||days>365)fail(400,'Die Laufzeit muss zwischen 1 und 365 Tagen liegen.');expires=now()+days*86400;if(input.maxUses!==''&&input.maxUses!==null&&input.maxUses!==undefined){maxUses=Number(input.maxUses);if(!Number.isInteger(maxUses)||maxUses<1||maxUses>500)fail(400,'Das Anfrage-Limit muss zwischen 1 und 500 liegen.');}}
 const after={status:input.status,expires,maxUses,uses:input.status==='open'?0:(before?.uses||0)};await env.DB.batch([stmt(env,"INSERT INTO join_settings(key,status,expires,max_uses,uses,updated_by,updated) VALUES('default',?,?,?,?,?,?) ON CONFLICT(key) DO UPDATE SET status=excluded.status,expires=excluded.expires,max_uses=excluded.max_uses,uses=excluded.uses,updated_by=excluded.updated_by,updated=excluded.updated",input.status,expires,maxUses,after.uses,actor.email,now()),stmt(env,'INSERT INTO audit VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),actor.email,'join_settings','join',JSON.stringify(before||{}),JSON.stringify(after),'applied',now(),'')]);return {message:input.status==='open'?'Beitrittslink geöffnet.':'Beitrittslink geschlossen.'};
}
export async function decideJoin(env,actor,input){
 const address=email(input.email);if(!['approve','reject'].includes(input.action))fail(400,'Ungültige Entscheidung.');const request=await one(env,"SELECT * FROM join_requests WHERE email=? AND status='pending'",address);if(!request)fail(404,'Offene Anfrage nicht gefunden.');if(input.action==='reject'){await env.DB.batch([stmt(env,"UPDATE join_requests SET status='rejected',reviewed=?,reviewed_by=? WHERE email=?",now(),actor.email,address),stmt(env,'INSERT INTO audit VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),actor.email,'join_reject',address,JSON.stringify({name:request.name,status:'pending'}),JSON.stringify({status:'rejected'}),'applied',now(),'')]);return {message:'Beitrittsanfrage abgelehnt.'};}
 const existing=await one(env,'SELECT * FROM members WHERE email=?',address);if(existing?.status==='revoked')fail(409,'Dieser Zugang ist gesperrt. Nur der Besitzer kann ihn in der Rollenverwaltung wieder freigeben.');if(!existing)await run(env,"INSERT INTO members(email,role,status,created) VALUES(?,'member','invited',?)",address,now());if(!existing||existing.status==='invited')await sendAccessLink(env,address,true);await env.DB.batch([stmt(env,"UPDATE join_requests SET status='approved',reviewed=?,reviewed_by=? WHERE email=?",now(),actor.email,address),stmt(env,'INSERT INTO audit VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),actor.email,'join_approve',address,JSON.stringify({name:request.name,status:'pending'}),JSON.stringify({role:'member',status:existing?.status||'invited'}),'applied',now(),'')]);return {message:existing?.status==='active'?'Anfrage freigegeben; der Zugang war bereits aktiv.':'Anfrage freigegeben und Anmeldelink versendet.'};
}
export async function verify(env,input){if(typeof input.token!=='string'||!/^[a-f0-9]{64}$/.test(input.token))fail(400,'Ungültiger Anmeldelink.');const token=await one(env,'DELETE FROM tokens WHERE hash=? AND expires>? RETURNING email',await hash(input.token),now());if(!token)fail(401,'Der Link ist abgelaufen oder bereits verwendet.');const session=random();
 const result=await env.DB.batch([stmt(env,"UPDATE members SET status='active' WHERE email=? AND status='invited'",token.email),stmt(env,'DELETE FROM login_codes WHERE email=?',token.email),stmt(env,"INSERT INTO sessions(hash,email,expires) SELECT ?,email,? FROM members WHERE email=? AND status='active'",await hash(session),now()+SESSION_AGE,token.email)]);
 if(result[2].meta.changes!==1)fail(403,'Dieser Zugang wurde zurückgezogen.');return session;
}
export async function verifyCode(request,env,input){const address=email(input.email);if(typeof input.code!=='string'||!/^\d{6}$/.test(input.code))fail(400,'Bitte gib den sechsstelligen Code ein.');await limit(env,'code-ip:'+request.headers.get('CF-Connecting-IP'),15);await limit(env,'code-email:'+address,8);const found=await one(env,'DELETE FROM login_codes WHERE hash=? AND email=? AND expires>? RETURNING email',await hash(address+':'+input.code),address,now());if(!found)fail(401,'Der Code ist falsch, abgelaufen oder bereits verwendet.');const session=random();const result=await env.DB.batch([stmt(env,"UPDATE members SET status='active' WHERE email=? AND status='invited'",address),stmt(env,'DELETE FROM tokens WHERE email=?',address),stmt(env,"INSERT INTO sessions(hash,email,expires) SELECT ?,email,? FROM members WHERE email=? AND status='active'",await hash(session),now()+SESSION_AGE,address)]);if(result[2].meta.changes!==1)fail(403,'Dieser Zugang wurde zurückgezogen.');return session;}
export async function logout(request,env){const t=request.headers.get('Cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);if(t)await run(env,'DELETE FROM sessions WHERE hash=?',await hash(t));}
export async function listMembers(env){return all(env,'SELECT email,role,status,created FROM members ORDER BY created,email');}
export async function invite(env,actor,input){const address=email(input.email);if(address===email(env.OWNER_EMAIL))fail(400,'Der Ligabesitzer ist bereits festgelegt.');const role=input.role;if(!['member','manager'].includes(role))fail(400,'Ungültige Rolle.');const existing=await one(env,'SELECT * FROM members WHERE email=?',address);if(existing&&existing.status!=='invited')fail(409,'Diese Adresse ist bereits erfasst. Nutze die Rollenverwaltung.');if(!existing)await env.DB.batch([stmt(env,"INSERT INTO members(email,role,status,created) VALUES(?,?,'invited',?)",address,role,now()),stmt(env,'INSERT INTO audit VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),actor.email,'invite',address,'{}',JSON.stringify({role,status:'invited'}),'applied',now(),'')]);await limit(env,'invite-email:'+address,3);await limit(env,'invite-global',100);await sendAccessLink(env,address,true);if(existing)await run(env,'INSERT INTO audit VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),actor.email,'invite_email',address,JSON.stringify({role:existing.role,status:existing.status}),JSON.stringify({emailSent:true}),'applied',now(),'');return {message:existing?'Einladung erneut versendet.':'Adresse freigegeben und Einladung versendet.'};}
export async function resendInvite(env,actor,input){const address=email(input.email);if(address===email(env.OWNER_EMAIL))fail(400,'Der Ligabesitzer benötigt keine Einladung.');const existing=await one(env,'SELECT email,role,status FROM members WHERE email=?',address);if(!existing)fail(404,'Mitglied nicht gefunden.');if(existing.role==='owner')fail(403,'Die Besitzerrolle kann hier nicht geändert werden.');if(existing.status==='revoked')fail(409,'Der Zugang ist entzogen. Gib ihn zuerst wieder frei.');await limit(env,'invite-email:'+address,3);await limit(env,'invite-global',100);await run(env,'DELETE FROM tokens WHERE email=?',address);await sendAccessLink(env,address,true);await run(env,'INSERT INTO audit VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),actor.email,'invite_email',address,JSON.stringify(existing),JSON.stringify({emailSent:true}),'applied',now(),'');return {message:'Einladung erneut versendet.'};}
export async function removeMember(env,actor,input){const address=email(input.email);if(address===actor.email||address===email(env.OWNER_EMAIL))fail(400,'Die Besitzerrolle bleibt erhalten.');const before=await one(env,'SELECT email,role,status FROM members WHERE email=?',address);if(!before)fail(404,'Mitglied nicht gefunden.');if(before.role==='owner')fail(403,'Die Besitzerrolle kann hier nicht entfernt werden.');await env.DB.batch([stmt(env,'DELETE FROM sessions WHERE email=?',address),stmt(env,'DELETE FROM tokens WHERE email=?',address),stmt(env,'DELETE FROM login_codes WHERE email=?',address),stmt(env,'DELETE FROM members WHERE email=?',address),stmt(env,'INSERT INTO audit VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),actor.email,'membership_remove',address,JSON.stringify(before),JSON.stringify({removed:true}),'applied',now(),'')]);return {message:'Zugang entfernt.'};}
export async function changeMember(env,actor,input){const address=email(input.email);if(address===actor.email||address===email(env.OWNER_EMAIL))fail(400,'Die Besitzerrolle bleibt erhalten.');if(!['member','manager'].includes(input.role)||!['active','revoked'].includes(input.status))fail(400,'Ungültige Rolle oder Status.');const before=await one(env,'SELECT email,role,status FROM members WHERE email=?',address);if(!before)fail(404,'Mitglied nicht gefunden.');if(before.role==='owner')fail(403,'Die Besitzerrolle kann hier nicht geändert werden.');const status=before.status==='invited'&&input.status==='active'?'invited':input.status;
 await env.DB.batch([stmt(env,'UPDATE members SET role=?,status=? WHERE email=?',input.role,status,address),stmt(env,'DELETE FROM sessions WHERE email=?',address),stmt(env,'DELETE FROM tokens WHERE email=?',address),stmt(env,'DELETE FROM login_codes WHERE email=?',address),stmt(env,'INSERT INTO audit VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),actor.email,'membership',address,JSON.stringify(before),JSON.stringify({role:input.role,status}),'applied',now(),'')]);return {message:'Zugang aktualisiert. Die Person meldet sich erneut an.'};}
