import {fail,hash} from './util.mjs';
import {League} from './scoring.mjs';
const encode=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
const utf=s=>new TextEncoder().encode(s);
async function access(env){if(!env.GOOGLE_SERVICE_ACCOUNT_EMAIL||!env.GOOGLE_PRIVATE_KEY||!env.SPREADSHEET_ID)fail(503,'Die Verbindung zur Tabelle wird noch eingerichtet.');const time=Math.floor(Date.now()/1000);const head=encode(utf(JSON.stringify({alg:'RS256',typ:'JWT'})));const claims=encode(utf(JSON.stringify({iss:env.GOOGLE_SERVICE_ACCOUNT_EMAIL,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:time,exp:time+3600})));const unsigned=head+'.'+claims;const pem=env.GOOGLE_PRIVATE_KEY.replace(/\\n/g,'\n').replace(/-----[^-]+-----/g,'').replace(/\s/g,'');const key=await crypto.subtle.importKey('pkcs8',Uint8Array.from(atob(pem),v=>v.charCodeAt(0)),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const signature=encode(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,utf(unsigned)));const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:unsigned+'.'+signature}),signal:AbortSignal.timeout(15000)});if(!r.ok)fail(503,'Google-Verbindung fehlgeschlagen.');return (await r.json()).access_token;}
export async function readSheet(env){if(env.SHEETS_TEST)return env.SHEETS_TEST.read();const token=await access(env);const q=new URLSearchParams({valueRenderOption:'UNFORMATTED_VALUE',dateTimeRenderOption:'SERIAL_NUMBER'});for(const r of ["'Spiele'!A1:N36","'Regeln'!B2:B12"])q.append('ranges',r);const response=await fetch('https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(env.SPREADSHEET_ID)+'/values:batchGet?'+q,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(15000)});if(!response.ok)fail(503,'Tabelle kann gerade nicht gelesen werden.');const result=await response.json();return {grid:result.valueRanges[0].values,rules:result.valueRanges[1].values};}
export async function writeBase(env,row,values){if(env.SHEETS_TEST)return env.SHEETS_TEST.write(row,values);const token=await access(env);const r=await fetch('https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(env.SPREADSHEET_ID)+'/values/'+encodeURIComponent(`'Spiele'!E${row}:L${row}`)+'?valueInputOption=RAW',{method:'PUT',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({values:[values]}),signal:AbortSignal.timeout(15000)});if(!r.ok)fail(503,'Speicherstatus unklar. Der Ligabesitzer muss die Änderung prüfen.');}
export async function snapshot(raw){
 const {grid}=raw;if(!grid||grid.length!==36||grid[0][0]!=='Spiel-ID'||grid[0][3]!=='Handicap-Modus'||grid[0][13]!=='Prüfung')fail(409,'Die Tabellenstruktur hat sich geändert.');const players=grid[0].slice(4,12);if(players.length!==8||players.some(p=>typeof p!=='string'||!p)||new Set(players).size!==8)fail(409,'Acht eindeutige Spielernamen erforderlich.');
 const v=raw.rules.map(r=>r[0]);const rules={start:v[0],low:v[1],high:v[2],normal:v[3],midFactor:v[4],highFactor:v[5],awards:v.slice(8,11)};
 if([rules.start,rules.low,rules.high,rules.normal,rules.midFactor,rules.highFactor,...rules.awards].some(x=>typeof x!=='number'||!Number.isFinite(x))||rules.low<0||rules.high<rules.low||rules.awards.some(x=>x<0))fail(409,'Regeln prüfen.');
 let totals=Array(8).fill(0),played=Array(8).fill(0),dayStart=[...totals],lastDay=0,lastDate=0,blank=false;const games=[],ids=new Set();
 grid.slice(1).forEach((r,i)=>{if(!Number.isInteger(r[0])||ids.has(r[0])||!Number.isInteger(r[2])||r[2]<lastDay||!Number.isFinite(r[1])||r[1]<lastDate||!['Pro Spiel','Pro Spieltag'].includes(r[3]))fail(409,'Reihenfolge, Datum oder Spiel-Einstellungen prüfen.');ids.add(r[0]);if(r[2]!==lastDay)dayStart=[...totals];lastDay=r[2];lastDate=r[1];const base=Array.from({length:8},(_,j)=>r[j+4]??'');const complete=base.some(x=>x!=='');const baseline=r[3]==='Pro Spieltag'?[...dayStart]:[...totals];if(complete){if(blank)fail(409,'Leere Spielzeile vor einem erfassten Spiel.');if(base.some(x=>x!==''&&(typeof x!=='number'||!Number.isFinite(x)||x<0||x>Math.max(...rules.awards)))||base.filter(x=>x!=='').length<3||Math.abs(base.reduce((s,x)=>s+(x===''?0:x),0)-rules.awards.reduce((a,b)=>a+b,0))>1e-8)fail(409,'Grundpunkte prüfen: Spiel '+r[0]);const leader=Math.max(...baseline);base.forEach((x,j)=>{if(x!==''){totals[j]+=x*League.factor(leader-baseline[j],r[2],rules);played[j]++;}});}else blank=true;games.push({id:r[0],row:i+2,day:r[2],date:new Date(Date.UTC(1899,11,30)+r[1]*86400000).toLocaleDateString('de-AT',{timeZone:'UTC'}),mode:r[3],baseline,base,complete});});
 return {players,totals,played,rules,games,game:games.find(g=>!g.complete)||null,revision:await hash(JSON.stringify(raw))};
}
